####################################################################################################
# This one performed better than the vectorizer
####################################################################################################
# PART 3 is to transfer the classes to df_data_phrases after verifying what part 2 did

import pandas as pd
import os
import sys
import config  # Import your configuration file

# --- 1. Path Definitions (from your config) ---

# File with class names generated by the LLM
FULL_PATH = f"{config.DATA_FOLDER}/directions_label_classified_full.csv"

# Main file where the data will be stored
DF_DATA_PATH_PARQUET = f"{config.DATA_FOLDER}/df_data_phrases.parquet"

# Final output in CSV
DF_DATA_PATH_CSV = f"{config.DATA_FOLDER}/df_data_phrases.csv"

def main():
    print("Starting classification merge script...")
    
    # --- 2. Load Files ---
    try:
        print(f"Loading classification file: {FULL_PATH}")
        df_classification = pd.read_csv(FULL_PATH)
        
        print(f"Loading target Parquet file: {DF_DATA_PATH_PARQUET}")
        df_target = pd.read_parquet(DF_DATA_PATH_PARQUET)
        
    except FileNotFoundError as e:
        print(f"\n[ERROR] File not found: {e.filename}")
        print("Please check if the paths in your 'config.py' are correct.")
        sys.exit(1)

    print("Files loaded successfully.")

    # --- 3. Prepare Source Data ---
    
    # Select only the necessary columns and rename 'class_name' to 'directions_group'
    # Ensures we have only one name per label by removing duplicates.
    df_source_map = df_classification[['directions_label', 'class_name']].rename(
        columns={'class_name': 'directions_group'}
    ).drop_duplicates(subset=['directions_label'])

    print("Classification data prepared and renamed to 'directions_group'.")

    # --- 4. Critical Validation ---
    print("Starting validation...")
    
    # Get the set of labels from the target file (Parquet)
    target_labels = set(df_target['directions_label'])
    
    # Get the set of labels from the source file (classification CSV)
    source_labels = set(df_source_map['directions_label'])
    
    # Check if there are any labels in the target that are NOT in the source
    missing_labels = target_labels - source_labels
    
    if len(missing_labels) > 0:
        print("\n" + "="*50)
        print(f"[FATAL ERROR] Execution interrupted.")
        print(f"{len(missing_labels)} 'directions_label' from the Parquet file were not found in the classification file.")
        print("This means the classification file is incomplete.")
        print("\nExamples of missing labels:")
        # Print the first 5 missing labels as an example
        for i, label in enumerate(list(missing_labels)):
            if i >= 5:
                break
            print(f"  - {label}")
        print("="*50)
        sys.exit(1) # Stop execution
    
    print("Validation completed successfully. All labels in the Parquet file have a corresponding classification.")

    # --- 5. Merge Data ---
    print("Starting data merge...")
    
    # Perform a 'left merge', bringing the 'directions_group' column into the df_target dataframe
    df_final = pd.merge(
        df_target,
        df_source_map,
        on='directions_label',
        how='left' # 'left' ensures we keep all rows from df_target
    )

    # Safety check (should not happen due to the validation above)
    if df_final['directions_group'].isnull().any():
        print("[WARNING] An unexpected error occurred and some 'directions_group' values are null after the merge.")
    else:
        print("Merge completed successfully. The 'directions_group' column has been added.")

    # --- 6. Save Final Files ---
    try:
        # 6a. Save in Parquet (overwriting the original)
        print(f"Saving updated data to Parquet: {DF_DATA_PATH_PARQUET}")
        df_final.to_parquet(DF_DATA_PATH_PARQUET, index=False)
        
        # 6b. Save in CSV
        print(f"Saving updated data to CSV: {DF_DATA_PATH_CSV}")
        # 'utf-8-sig' is recommended for CSVs to open correctly in Excel
        df_final.to_csv(DF_DATA_PATH_CSV, index=False, encoding='utf-8-sig')

    except Exception as e:
        print(f"\n[ERROR] Failed to save final files: {e}")
        sys.exit(1)
        
    print("\n" + "="*50)
    print("✅ Process completed successfully!")
    print("The Parquet file has been updated and a new CSV file has been generated.")
    print("="*50)

if __name__ == "__main__":
    main()
